name: Streamlit CI/CD

on:
  push:
    branches:
      - main  # or whatever your main branch is

jobs:
  streamlit-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python (optional)
        run: |
          pip install flake8
          flake8 aqi.py

      - name: ✅ Deployment (Streamlit Auto Updates)
        run: echo "Push complete — Streamlit Cloud will auto-redeploy from GitHub."
